# fly.toml app configuration file generated for shopify-2024 on 2024-05-19T20:20:42+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'shopify-2024'
primary_region = 'cdg'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
